// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AddQuestionTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void addQuestion() {
    driver.Navigate().GoToUrl("http://localhost:3000/AddQuestions");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 824);
    driver.FindElement(By.CssSelector(".border:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".border:nth-child(3)")).SendKeys("21");
    driver.FindElement(By.CssSelector(".border:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".border:nth-child(2)")).SendKeys("How is your capstone project experience using java");
    driver.FindElement(By.CssSelector(".border:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".border:nth-child(1)")).SendKeys("Excellent");
    driver.FindElement(By.CssSelector(".px-2:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".flex:nth-child(4) > .border")).Click();
    driver.FindElement(By.CssSelector(".flex:nth-child(4) > .border")).SendKeys("Good");
    driver.FindElement(By.CssSelector(".px-2:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".flex:nth-child(5) > .border")).Click();
    driver.FindElement(By.CssSelector(".flex:nth-child(5) > .border")).SendKeys("Average");
    driver.FindElement(By.CssSelector(".bg-green-500")).Click();
  }
}
