// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AddResponsetoSurveyTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void addResponsetoSurvey() {
    driver.Navigate().GoToUrl("http://localhost:3000/SurveyDetails/b0aba08b-3e66-4aec-a5f1-3418a50d63ae");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.CssSelector(".mb-2:nth-child(2) .form-radio")).Click();
    driver.FindElement(By.CssSelector(".hover\\3A bg-blue-600")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("your Response has been recorded successfully!"));
  }
}
