// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AddSurveyTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void addSurvey() {
    driver.Navigate().GoToUrl("http://localhost:3000/Surveyform");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 824);
    driver.FindElement(By.Name("Title")).Click();
    driver.FindElement(By.Name("Title")).SendKeys("Relevantz Survey ");
    driver.FindElement(By.Name("Description")).Click();
    driver.FindElement(By.Name("Description")).SendKeys("Share your feeback about working experience at Relevantz");
    driver.FindElement(By.CssSelector(".bg-green-500")).Click();
  }
}
